/* HOMEOFTEN shared data — generated. Edit catalog.json + rerun if you change products. */
window.HOMEOFTEN = window.HOMEOFTEN || {};

window.HOMEOFTEN.CATALOG = {
  "kit001": {"sku":"kit001","section":"Kitchen","name":"Filtered Living Water Machine","price":59.99,"image":"images/kit001.png","source":"https://crossbeez.com/product?id=688"},
  "kit002": {"sku":"kit002","section":"Kitchen","name":"Heating tea water mobile power supply","price":76.98,"image":"images/kit002.png","source":"https://crossbeez.com/product?id=746"},
  "kit003": {"sku":"kit003","section":"Kitchen","name":"Warm cup coffee heating pad","price":89.98,"image":"images/kit003.jpg","source":"https://crossbeez.com/product?id=753"},
  "kit004": {"sku":"kit004","section":"Kitchen","name":"400ML intelligent portable boiling electric cup","price":29.99,"image":"images/kit004.jpg","source":"https://crossbeez.com/product?id=783"},
  "kit005": {"sku":"kit005","section":"Kitchen","name":"1.0L slim mouth temperature controlled electric kettle","price":69.99,"image":"images/kit005.jpg","source":"https://crossbeez.com/product?id=784"},
  "kit006": {"sku":"kit006","section":"Kitchen","name":"0.8L temperature control heating stainless steel kettle","price":54.98,"image":"images/kit006.jpg","source":"https://crossbeez.com/product?id=785"},
  "kit007": {"sku":"kit007","section":"Kitchen","name":"Smart water dispenser","price":94.98,"image":"images/kit007.jpg","source":"https://crossbeez.com/product?id=786"},
  "kit008": {"sku":"kit008","section":"Kitchen","name":"Small electric kettle with a capacity of 1.7L","price":58.16,"image":"images/kit008.jpg","source":"https://crossbeez.com/product?id=787"},
  "kit009": {"sku":"kit009","section":"Kitchen","name":"Three-in-one automatic water-feeding tea maker","price":134.98,"image":"images/kit009.jpg","source":"https://crossbeez.com/product?id=788"},
  "kit010": {"sku":"kit010","section":"Kitchen","name":"Portable Electric Kettle","price":49.99,"image":"images/kit010.jpg","source":"https://crossbeez.com/product?id=789"},
  "kit011": {"sku":"kit011","section":"Kitchen","name":"1500ML stainless steel inner liner automatic electric kettle","price":68.99,"image":"images/kit011.jpg","source":"https://crossbeez.com/product?id=790"},
  "kit012": {"sku":"kit012","section":"Kitchen","name":"400ml Portable Wireless Rechargeable Electric Kettle","price":124.65,"image":"images/kit012.jpg","source":"https://crossbeez.com/product?id=791"},
  "kit013": {"sku":"kit013","section":"Kitchen","name":"Portable Folding Water Kettle","price":99.51,"image":"images/kit013.jpg","source":"https://crossbeez.com/product?id=796"},
  "kit014": {"sku":"kit014","section":"Kitchen","name":"Automatic power-off scalding-proof electric kettle","price":60.65,"image":"images/kit014.png","source":"https://crossbeez.com/product?id=797"},
  "kit015": {"sku":"kit015","section":"Kitchen","name":"1.7L stainless steel electric kettle","price":78.67,"image":"images/kit015.jpg","source":"https://crossbeez.com/product?id=798"},
  "kit016": {"sku":"kit016","section":"Kitchen","name":"Large-capacity vehicle-mounted electric kettle is insulat...","price":121.67,"image":"images/kit016.jpg","source":"https://crossbeez.com/product?id=799"},
  "kit017": {"sku":"kit017","section":"Kitchen","name":"Digital intelligent travel coffee thermal insulation touc...","price":69.37,"image":"images/kit017.jpg","source":"https://crossbeez.com/product?id=800"},
  "kit018": {"sku":"kit018","section":"Kitchen","name":"1.7 Liter Plastic Electric Kettle, White","price":43.28,"image":"images/kit018.jpg","source":"https://crossbeez.com/product?id=801"},
  "kit019": {"sku":"kit019","section":"Kitchen","name":"Milk tea water heating coaster","price":33.88,"image":"images/kit019.webp","source":"https://crossbeez.com/product?id=811"},
  "kit020": {"sku":"kit020","section":"Kitchen","name":"Heat-insulating and heating drink coasters","price":35.97,"image":"images/kit020.webp","source":"https://crossbeez.com/product?id=812"},
  "kit021": {"sku":"kit021","section":"Kitchen","name":"Coffee milk cup portable heating coasters","price":39.99,"image":"images/kit021.webp","source":"https://crossbeez.com/product?id=813"},
  "kit022": {"sku":"kit022","section":"Kitchen","name":"Intelligent coffee cup timing electric coaster","price":35,"image":"images/kit022.webp","source":"https://crossbeez.com/product?id=814"},
  "kit023": {"sku":"kit023","section":"Kitchen","name":"Coffee cup timing tea maker heats coasters","price":54.98,"image":"images/kit023.webp","source":"https://crossbeez.com/product?id=816"},
  "kit024": {"sku":"kit024","section":"Kitchen","name":"Coffee, drink, milk heating coaster","price":44.52,"image":"images/kit024.webp","source":"https://crossbeez.com/product?id=817"},
  "kit025": {"sku":"kit025","section":"Kitchen","name":"Small stainless steel electric kettle","price":79.99,"image":"images/kit025.jpg","source":"https://crossbeez.com/product?id=857"},
  "kit026": {"sku":"kit026","section":"Kitchen","name":"0.5 liter portable electric kettle","price":53.62,"image":"images/kit026.jpg","source":"https://crossbeez.com/product?id=858"},
  "kit027": {"sku":"kit027","section":"Kitchen","name":"Portable tea and coffee maker mini travel electric kettle","price":46.85,"image":"images/kit027.jpg","source":"https://crossbeez.com/product?id=859"},
  "kit028": {"sku":"kit028","section":"Kitchen","name":"Home Kitchen Waffles","price":25.99,"image":"images/kit028.webp","source":"https://crossbeez.com/product?id=950"},
  "kit029": {"sku":"kit029","section":"Kitchen","name":"Panini waffle and sandwich machine","price":27.89,"image":"images/kit029.webp","source":"https://crossbeez.com/product?id=951"},
  "kit030": {"sku":"kit030","section":"Kitchen","name":"Heart Shaped Waffle Maker","price":17.99,"image":"images/kit030.webp","source":"https://crossbeez.com/product?id=952"},
  "kit031": {"sku":"kit031","section":"Kitchen","name":"Small home pancake maker","price":13.99,"image":"images/kit031.webp","source":"https://crossbeez.com/product?id=953"},
  "kit032": {"sku":"kit032","section":"Kitchen","name":"Home air fryer","price":59.99,"image":"images/kit032.webp","source":"https://crossbeez.com/product?id=954"},
  "kit033": {"sku":"kit033","section":"Kitchen","name":"Electric air fryer","price":69.99,"image":"images/kit033.webp","source":"https://crossbeez.com/product?id=955"},
  "kit034": {"sku":"kit034","section":"Kitchen","name":"Air Fryer in 4 liters","price":69.99,"image":"images/kit034.webp","source":"https://crossbeez.com/product?id=956"},
  "kit035": {"sku":"kit035","section":"Kitchen","name":"5 in 1 Indoor Grill with Air Fryer","price":129.99,"image":"images/kit035.webp","source":"https://crossbeez.com/product?id=957"},
  "kit036": {"sku":"kit036","section":"Kitchen","name":"Super Air Fryer 10 Lts","price":139.99,"image":"images/kit036.webp","source":"https://crossbeez.com/product?id=958"},
  "kit037": {"sku":"kit037","section":"Kitchen","name":"Small household bread machine","price":32.99,"image":"images/kit037.webp","source":"https://crossbeez.com/product?id=959"},
  "kit038": {"sku":"kit038","section":"Kitchen","name":"4-slice toaster","price":59.89,"image":"images/kit038.webp","source":"https://crossbeez.com/product?id=960"},
  "kit039": {"sku":"kit039","section":"Kitchen","name":"2 slice toaster","price":24.99,"image":"images/kit039.webp","source":"https://crossbeez.com/product?id=961"},
  "kit040": {"sku":"kit040","section":"Kitchen","name":"2 slice toaster heats quickly","price":24.99,"image":"images/kit040.webp","source":"https://crossbeez.com/product?id=962"},
  "kit041": {"sku":"kit041","section":"Kitchen","name":"650 W Small toaster","price":19.99,"image":"images/kit041.webp","source":"https://crossbeez.com/product?id=963"},
  "kit042": {"sku":"kit042","section":"Kitchen","name":"2 Slice Stainless Steel Toaster","price":36.99,"image":"images/kit042.webp","source":"https://crossbeez.com/product?id=964"},
  "kit043": {"sku":"kit043","section":"Kitchen","name":"Reversible Touch Screen Blender","price":109.99,"image":"images/kit043.webp","source":"https://crossbeez.com/product?id=965"},
  "kit044": {"sku":"kit044","section":"Kitchen","name":"Citrus Juicer Stainless Steel","price":69.99,"image":"images/kit044.webp","source":"https://crossbeez.com/product?id=966"},
  "kit045": {"sku":"kit045","section":"Kitchen","name":"The 800-watt Juicer","price":79.99,"image":"images/kit045.webp","source":"https://crossbeez.com/product?id=968"},
  "kit046": {"sku":"kit046","section":"Kitchen","name":"Fruit and vegetable juicer","price":97.29,"image":"images/kit046.webp","source":"https://crossbeez.com/product?id=970"},
  "kit047": {"sku":"kit047","section":"Kitchen","name":"Cold Pressed Fruit and Vegetable Juice Extractor","price":78.99,"image":"images/kit047.webp","source":"https://crossbeez.com/product?id=971"},
  "kit048": {"sku":"kit048","section":"Kitchen","name":"The Citrus Juicer","price":11.99,"image":"images/kit048.webp","source":"https://crossbeez.com/product?id=972"},
  "kit049": {"sku":"kit049","section":"Kitchen","name":"1.5 Lts Premium Kettle","price":49.99,"image":"images/kit049.webp","source":"https://crossbeez.com/product?id=973"},
  "kit050": {"sku":"kit050","section":"Kitchen","name":"Ergonomically designed electric kettle","price":21.99,"image":"images/kit050.webp","source":"https://crossbeez.com/product?id=974"},
  "kit051": {"sku":"kit051","section":"Kitchen","name":"1.5L Electric Kettle","price":38.99,"image":"images/kit051.webp","source":"https://crossbeez.com/product?id=975"},
  "kit052": {"sku":"kit052","section":"Kitchen","name":"With LED display Kettle","price":22.99,"image":"images/kit052.webp","source":"https://crossbeez.com/product?id=976"},
  "kit053": {"sku":"kit053","section":"Kitchen","name":"Controlled Warming Cup","price":54.98,"image":"images/kit053.png","source":"https://crossbeez.com/product?id=1013"},
  "kit054": {"sku":"kit054","section":"Kitchen","name":"Espresso machine","price":134.98,"image":"images/kit054.jpg","source":"https://crossbeez.com/product?id=1065"},
  "kit055": {"sku":"kit055","section":"Kitchen","name":"Household fully automatic coffee machine","price":116.49,"image":"images/kit055.png","source":"https://crossbeez.com/product?id=1066"},
  "kit056": {"sku":"kit056","section":"Kitchen","name":"Commercial coffee machine","price":148,"image":"images/kit056.jpg","source":"https://crossbeez.com/product?id=1067"},
  "kit057": {"sku":"kit057","section":"Kitchen","name":"Espresso machine, 47 fluid ounces","price":127,"image":"images/kit057.jpg","source":"https://crossbeez.com/product?id=1068"},
  "kit058": {"sku":"kit058","section":"Kitchen","name":"Capsule coffee machine","price":116.69,"image":"images/kit058.jpg","source":"https://crossbeez.com/product?id=1069"},
  "kit059": {"sku":"kit059","section":"Kitchen","name":"Drip coffee machine","price":169.69,"image":"images/kit059.png","source":"https://crossbeez.com/product?id=1070"},
  "kit060": {"sku":"kit060","section":"Kitchen","name":"10 cups drip-free coffee machine","price":189,"image":"images/kit060.jpg","source":"https://crossbeez.com/product?id=1071"},
  "kit061": {"sku":"kit061","section":"Kitchen","name":"Adjustable grinding coffee machine","price":125,"image":"images/kit061.jpg","source":"https://crossbeez.com/product?id=1072"},
  "kit062": {"sku":"kit062","section":"Kitchen","name":"Coffee machine / coffee maker","price":116.89,"image":"images/kit062.jpg","source":"https://crossbeez.com/product?id=1073"},
  "kit063": {"sku":"kit063","section":"Kitchen","name":"Coffee machine, 12 cups","price":154.69,"image":"images/kit063.jpg","source":"https://crossbeez.com/product?id=1074"},
  "kit064": {"sku":"kit064","section":"Kitchen","name":"700G blender.","price":46.95,"image":"images/kit064.jpg","source":"https://crossbeez.com/product?id=1075"},
  "kit065": {"sku":"kit065","section":"Kitchen","name":"Slow juicer","price":56.36,"image":"images/kit065.png","source":"https://crossbeez.com/product?id=1076"},
  "kit066": {"sku":"kit066","section":"Kitchen","name":"Intelligent mixer","price":69.55,"image":"images/kit066.jpg","source":"https://crossbeez.com/product?id=1077"},
  "kit067": {"sku":"kit067","section":"Kitchen","name":"Electric citrus juicer","price":29.99,"image":"images/kit067.jpg","source":"https://crossbeez.com/product?id=1078"},
  "kit068": {"sku":"kit068","section":"Kitchen","name":"Portable Blender","price":32.26,"image":"images/kit068.jpg","source":"https://crossbeez.com/product?id=1079"},
  "kit069": {"sku":"kit069","section":"Kitchen","name":"Personal mixer","price":75.89,"image":"images/kit069.jpg","source":"https://crossbeez.com/product?id=1080"},
  "kit070": {"sku":"kit070","section":"Kitchen","name":"Portable mixer","price":33.59,"image":"images/kit070.jpg","source":"https://crossbeez.com/product?id=1081"},
  "kit071": {"sku":"kit071","section":"Kitchen","name":"Personal smoothie mixer","price":39.99,"image":"images/kit071.jpg","source":"https://crossbeez.com/product?id=1082"},
  "kit072": {"sku":"kit072","section":"Kitchen","name":"Professional kitchen mixer","price":52.29,"image":"images/kit072.jpg","source":"https://crossbeez.com/product?id=1083"},
  "kit073": {"sku":"kit073","section":"Kitchen","name":"Smoothie mixer","price":49.56,"image":"images/kit073.jpg","source":"https://crossbeez.com/product?id=1084"},
  "cln001": {"sku":"cln001","section":"Cleaning","name":"Household vacuum, sweep and mop all-in-one silent","price":159.99,"image":"images/cln001.jpg","source":"https://crossbeez.com/product?id=756"},
  "cln002": {"sku":"cln002","section":"Cleaning","name":"Smart sweeping robot for home use","price":165.66,"image":"images/cln002.jpg","source":"https://crossbeez.com/product?id=757"},
  "cln003": {"sku":"cln003","section":"Cleaning","name":"Smart floor mopping vacuum cleaner","price":209.98,"image":"images/cln003.jpg","source":"https://crossbeez.com/product?id=758"},
  "cln004": {"sku":"cln004","section":"Cleaning","name":"USB rechargeable automatic cleaning machine","price":189.98,"image":"images/cln004.jpg","source":"https://crossbeez.com/product?id=759"},
  "cln005": {"sku":"cln005","section":"Cleaning","name":"Fully automatic sweeping robot","price":209.99,"image":"images/cln005.jpg","source":"https://crossbeez.com/product?id=760"},
  "cln006": {"sku":"cln006","section":"Cleaning","name":"Lazy sweeper silent vacuum cleaner","price":72.98,"image":"images/cln006.jpg","source":"https://crossbeez.com/product?id=761"},
  "cln007": {"sku":"cln007","section":"Cleaning","name":"Household sweeping robot intelligent cleaning","price":110.99,"image":"images/cln007.jpg","source":"https://crossbeez.com/product?id=762"},
  "cln008": {"sku":"cln008","section":"Cleaning","name":"Ultra-quiet intelligent robot vacuum cleaner wet and dry ...","price":49.99,"image":"images/cln008.jpg","source":"https://crossbeez.com/product?id=802"},
  "cln009": {"sku":"cln009","section":"Cleaning","name":"3-in-1 intelligent sweeping robot home mini sweeper","price":59,"image":"images/cln009.webp","source":"https://crossbeez.com/product?id=803"},
  "cln010": {"sku":"cln010","section":"Cleaning","name":"Intelligent sweeping robot big water tank mobile phone Ap...","price":36.65,"image":"images/cln010.jpg","source":"https://crossbeez.com/product?id=804"},
  "cln011": {"sku":"cln011","section":"Cleaning","name":"5-in-1 robot vacuum cleaner USB charging automatic cleani...","price":65,"image":"images/cln011.webp","source":"https://crossbeez.com/product?id=805"},
  "cln012": {"sku":"cln012","section":"Cleaning","name":"Intelligent remote control APP wireless sweeping robot","price":75.82,"image":"images/cln012.jpg","source":"https://crossbeez.com/product?id=806"},
  "cln013": {"sku":"cln013","section":"Cleaning","name":"3 in 1 robot sweeping robot","price":94.98,"image":"images/cln013.webp","source":"https://crossbeez.com/product?id=807"},
  "cln014": {"sku":"cln014","section":"Cleaning","name":"USB charging intelligent sweeping robot","price":149,"image":"images/cln014.jpg","source":"https://crossbeez.com/product?id=808"},
  "cln015": {"sku":"cln015","section":"Cleaning","name":"Silent Multi-Function integrated wet and dry mopping robot","price":77,"image":"images/cln015.webp","source":"https://crossbeez.com/product?id=810"},
  "cln016": {"sku":"cln016","section":"Cleaning","name":"Sweeping robot for wet and dry use","price":117.5,"image":"images/cln016.webp","source":"https://crossbeez.com/product?id=848"},
  "cln017": {"sku":"cln017","section":"Cleaning","name":"Cordless high-power wet and dry vacuum cleaner","price":135.07,"image":"images/cln017.png","source":"https://crossbeez.com/product?id=849"},
  "cln018": {"sku":"cln018","section":"Cleaning","name":"Handheld rechargeable vacuum cleaner","price":107.98,"image":"images/cln018.webp","source":"https://crossbeez.com/product?id=850"},
  "cln019": {"sku":"cln019","section":"Cleaning","name":"Cordless handheld rechargeable automatic vacuum cleaner","price":132.98,"image":"images/cln019.png","source":"https://crossbeez.com/product?id=851"},
  "cln020": {"sku":"cln020","section":"Cleaning","name":"USB robot vacuum cleaner","price":132.32,"image":"images/cln020.webp","source":"https://crossbeez.com/product?id=852"},
  "cln021": {"sku":"cln021","section":"Cleaning","name":"WiFi/Bluetooth sweeping robot","price":135.57,"image":"images/cln021.webp","source":"https://crossbeez.com/product?id=853"},
  "cln022": {"sku":"cln022","section":"Cleaning","name":"Cordless Silent Portable Vacuum Cleaner","price":89.94,"image":"images/cln022.png","source":"https://crossbeez.com/product?id=854"},
  "cln023": {"sku":"cln023","section":"Cleaning","name":"2 in 1 mopping robot vacuum cleaner","price":169.99,"image":"images/cln023.jpg","source":"https://crossbeez.com/product?id=855"},
  "cln024": {"sku":"cln024","section":"Cleaning","name":"Vacuum automatic charging mopping robot","price":167.99,"image":"images/cln024.jpg","source":"https://crossbeez.com/product?id=856"},
  "cln025": {"sku":"cln025","section":"Cleaning","name":"Easy Cleaning Slow Juicer","price":89.99,"image":"images/cln025.webp","source":"https://crossbeez.com/product?id=969"},
  "cln026": {"sku":"cln026","section":"Cleaning","name":"Fully Automatic Floor Sweeper","price":29.99,"image":"images/cln026.png","source":"https://crossbeez.com/product?id=994"},
  "cln027": {"sku":"cln027","section":"Cleaning","name":"Intelligent Floor Sweeper","price":49.99,"image":"images/cln027.png","source":"https://crossbeez.com/product?id=995"},
  "cln028": {"sku":"cln028","section":"Cleaning","name":"Silent Automatic Floor Sweeper","price":69.99,"image":"images/cln028.png","source":"https://crossbeez.com/product?id=996"},
  "cln029": {"sku":"cln029","section":"Cleaning","name":"Rechargeable Floor Sweeper","price":54.98,"image":"images/cln029.jpg","source":"https://crossbeez.com/product?id=997"},
  "cln030": {"sku":"cln030","section":"Cleaning","name":"Home Sweeper","price":94.98,"image":"images/cln030.png","source":"https://crossbeez.com/product?id=998"},
  "cln031": {"sku":"cln031","section":"Cleaning","name":"Silent Floor Sweeper","price":134.98,"image":"images/cln031.png","source":"https://crossbeez.com/product?id=999"},
  "cln032": {"sku":"cln032","section":"Cleaning","name":"High-powered Floor Sweeper","price":89.98,"image":"images/cln032.png","source":"https://crossbeez.com/product?id=1000"},
  "cln033": {"sku":"cln033","section":"Cleaning","name":"No-wash Floor Sweeper","price":105.98,"image":"images/cln033.png","source":"https://crossbeez.com/product?id=1001"},
  "cln034": {"sku":"cln034","section":"Cleaning","name":"Rechargeable Spray Mopping Robot","price":79.98,"image":"images/cln034.png","source":"https://crossbeez.com/product?id=1002"},
  "cln035": {"sku":"cln035","section":"Cleaning","name":"Ultra-quiet intelligent robot vacuum cleaner","price":149.23,"image":"images/cln035.jpg","source":"https://crossbeez.com/product?id=1003"},
  "cln036": {"sku":"cln036","section":"Cleaning","name":"Household mini sweeper","price":129.37,"image":"images/cln036.webp","source":"https://crossbeez.com/product?id=1004"},
  "cln037": {"sku":"cln037","section":"Cleaning","name":"Remote control of intelligent sweeping robot mobile App","price":137.6,"image":"images/cln037.jpg","source":"https://crossbeez.com/product?id=1005"},
  "cln038": {"sku":"cln038","section":"Cleaning","name":"USB charging automatic cleaning sweeper","price":158.9,"image":"images/cln038.webp","source":"https://crossbeez.com/product?id=1006"},
  "cln039": {"sku":"cln039","section":"Cleaning","name":"ES06 intelligent remote control APP wireless sweeping robot","price":129.9,"image":"images/cln039.jpg","source":"https://crossbeez.com/product?id=1007"},
  "cln040": {"sku":"cln040","section":"Cleaning","name":"Silent floor scrubber of intelligent mopping robot","price":150.98,"image":"images/cln040.webp","source":"https://crossbeez.com/product?id=1008"},
  "cln041": {"sku":"cln041","section":"Cleaning","name":"Household mini smart vacuum cleaner sweeping robot","price":121.88,"image":"images/cln041.webp","source":"https://crossbeez.com/product?id=1009"},
  "cln042": {"sku":"cln042","section":"Cleaning","name":"Household air cleaner","price":86.55,"image":"images/cln042.png","source":"https://crossbeez.com/product?id=1085"},
  "cln043": {"sku":"cln043","section":"Cleaning","name":"Air cleaner","price":117.68,"image":"images/cln043.png","source":"https://crossbeez.com/product?id=1088"},
  "cln044": {"sku":"cln044","section":"Cleaning","name":"Household large room air cleaner","price":152,"image":"images/cln044.png","source":"https://crossbeez.com/product?id=1089"},
  "cln045": {"sku":"cln045","section":"Cleaning","name":"Air quality monitoring air cleaner","price":95.65,"image":"images/cln045.png","source":"https://crossbeez.com/product?id=1090"},
  "pet001": {"sku":"pet001","section":"Pet","name":"Automatic Pet Feeder","price":29.99,"image":"images/pet001.png","source":"https://crossbeez.com/product?id=681"},
  "pet002": {"sku":"pet002","section":"Pet","name":"Timed Dosing Feeder","price":49.99,"image":"images/pet002.png","source":"https://crossbeez.com/product?id=682"},
  "pet003": {"sku":"pet003","section":"Pet","name":"Smart Pet Feeder","price":69.99,"image":"images/pet003.png","source":"https://crossbeez.com/product?id=683"},
  "pet004": {"sku":"pet004","section":"Pet","name":"WIFI Automatic Feeder","price":54.98,"image":"images/pet004.png","source":"https://crossbeez.com/product?id=684"},
  "pet005": {"sku":"pet005","section":"Pet","name":"Timed Pet Feeder","price":94.98,"image":"images/pet005.png","source":"https://crossbeez.com/product?id=685"},
  "pet006": {"sku":"pet006","section":"Pet","name":"Roman Column Pet Feeder","price":134.98,"image":"images/pet006.png","source":"https://crossbeez.com/product?id=686"},
  "pet007": {"sku":"pet007","section":"Pet","name":"Pet Water Dispenser","price":75.99,"image":"images/pet007.png","source":"https://crossbeez.com/product?id=687"},
  "pet008": {"sku":"pet008","section":"Pet","name":"Cute Cat Humidifier","price":39.99,"image":"images/pet008.png","source":"https://crossbeez.com/product?id=721"},
  "pet009": {"sku":"pet009","section":"Pet","name":"Cute pet artifact plug-in creative instant coaster","price":147.91,"image":"images/pet009.jpg","source":"https://crossbeez.com/product?id=749"},
  "pet010": {"sku":"pet010","section":"Pet","name":"Six-hole pet smart feeder","price":99.99,"image":"images/pet010.jpg","source":"https://crossbeez.com/product?id=763"},
  "pet011": {"sku":"pet011","section":"Pet","name":"4L smart pet feeder","price":89.9,"image":"images/pet011.jpg","source":"https://crossbeez.com/product?id=764"},
  "pet012": {"sku":"pet012","section":"Pet","name":"Automatic cat feeding water feeder","price":110.92,"image":"images/pet012.jpg","source":"https://crossbeez.com/product?id=765"},
  "pet013": {"sku":"pet013","section":"Pet","name":"Pet smart feeder timing and rationing","price":76.99,"image":"images/pet013.jpg","source":"https://crossbeez.com/product?id=766"},
  "pet014": {"sku":"pet014","section":"Pet","name":"Dog water dispenser cat automatic feeder","price":25.98,"image":"images/pet014.jpg","source":"https://crossbeez.com/product?id=767"},
  "pet015": {"sku":"pet015","section":"Pet","name":"Baby cat feeder","price":88.99,"image":"images/pet015.jpg","source":"https://crossbeez.com/product?id=768"},
  "pet016": {"sku":"pet016","section":"Pet","name":"Cream hanging drinking water feeder","price":77.99,"image":"images/pet016.jpg","source":"https://crossbeez.com/product?id=769"},
  "pet017": {"sku":"pet017","section":"Pet","name":"Pet automatic feeder water dispenser set","price":36.53,"image":"images/pet017.webp","source":"https://crossbeez.com/product?id=779"},
  "pet018": {"sku":"pet018","section":"Pet","name":"Automatic pet feeder water dispenser","price":118.6,"image":"images/pet018.webp","source":"https://crossbeez.com/product?id=780"},
  "pet019": {"sku":"pet019","section":"Pet","name":"Led lamp USB powered 2L pet water dispenser","price":54.32,"image":"images/pet019.jpg","source":"https://crossbeez.com/product?id=781"},
  "pet020": {"sku":"pet020","section":"Pet","name":"Double meal camera feeder","price":126.89,"image":"images/pet020.webp","source":"https://crossbeez.com/product?id=782"},
  "pet021": {"sku":"pet021","section":"Pet","name":"Cute Cat Constant Warm Coaster","price":49.99,"image":"images/pet021.png","source":"https://crossbeez.com/product?id=1011"},
  "pet022": {"sku":"pet022","section":"Pet","name":"Cat small humidifier","price":105,"image":"images/pet022.png","source":"https://crossbeez.com/product?id=1108"},
  "per001": {"sku":"per001","section":"Personal Care","name":"Electric shaver","price":54.98,"image":"images/per001.png","source":"https://crossbeez.com/product?id=696"},
  "per002": {"sku":"per002","section":"Personal Care","name":"Portable shaver","price":69.99,"image":"images/per002.png","source":"https://crossbeez.com/product?id=697"},
  "per003": {"sku":"per003","section":"Personal Care","name":"Electric rechargeable shaver","price":29.99,"image":"images/per003.jpg","source":"https://crossbeez.com/product?id=699"},
  "per004": {"sku":"per004","section":"Personal Care","name":"Negative ion constant temperature high speed hair dryer","price":134.98,"image":"images/per004.png","source":"https://crossbeez.com/product?id=700"},
  "per005": {"sku":"per005","section":"Personal Care","name":"Quick heat non-damaging portable curling iron","price":94.98,"image":"images/per005.png","source":"https://crossbeez.com/product?id=701"},
  "per006": {"sku":"per006","section":"Personal Care","name":"Hairdressing bangs splint Multi-Function hair straightene...","price":56.98,"image":"images/per006.png","source":"https://crossbeez.com/product?id=702"},
  "per007": {"sku":"per007","section":"Personal Care","name":"Straightening electric splint without damaging hair","price":89.98,"image":"images/per007.png","source":"https://crossbeez.com/product?id=703"},
  "per008": {"sku":"per008","section":"Personal Care","name":"French Wave Curling Iron","price":61,"image":"images/per008.jpg","source":"https://crossbeez.com/product?id=770"},
  "per009": {"sku":"per009","section":"Personal Care","name":"One Step Hair Dryer 5 IN 1","price":179,"image":"images/per009.jpg","source":"https://crossbeez.com/product?id=771"},
  "per010": {"sku":"per010","section":"Personal Care","name":"💖Negative Ion Hair Straightener Styling Comb","price":129,"image":"images/per010.jpg","source":"https://crossbeez.com/product?id=772"},
  "per011": {"sku":"per011","section":"Personal Care","name":"Two-in-one hair straightener and curling iron","price":119,"image":"images/per011.webp","source":"https://crossbeez.com/product?id=773"},
  "per012": {"sku":"per012","section":"Personal Care","name":"Electric curling iron curling iron","price":89.98,"image":"images/per012.webp","source":"https://crossbeez.com/product?id=774"},
  "per013": {"sku":"per013","section":"Personal Care","name":"5-in-1 ultrasonic hair dryer hot comb professional curlin...","price":156,"image":"images/per013.webp","source":"https://crossbeez.com/product?id=775"},
  "per014": {"sku":"per014","section":"Personal Care","name":"25mm ceramic automatic curling iron","price":99.98,"image":"images/per014.jpg","source":"https://crossbeez.com/product?id=776"},
  "per015": {"sku":"per015","section":"Personal Care","name":"Whole body depilation instrument","price":29.99,"image":"images/per015.jpg","source":"https://crossbeez.com/product?id=834"},
  "per016": {"sku":"per016","section":"Personal Care","name":"4-in-1 electric rechargeable hair removal instrument","price":69.99,"image":"images/per016.jpg","source":"https://crossbeez.com/product?id=835"},
  "per017": {"sku":"per017","section":"Personal Care","name":"Portable electric full-body shaver charging depilation in...","price":26.82,"image":"images/per017.jpg","source":"https://crossbeez.com/product?id=836"},
  "per018": {"sku":"per018","section":"Personal Care","name":"Painless electric depilator","price":36.56,"image":"images/per018.jpg","source":"https://crossbeez.com/product?id=837"},
  "per019": {"sku":"per019","section":"Personal Care","name":"Lady's electric rechargeable depilation instrument","price":94.98,"image":"images/per019.jpg","source":"https://crossbeez.com/product?id=838"},
  "per020": {"sku":"per020","section":"Personal Care","name":"Women's Electric Shaver 2 in 1 Full Body Hair Removal Device","price":66.65,"image":"images/per020.jpg","source":"https://crossbeez.com/product?id=840"},
  "per021": {"sku":"per021","section":"Personal Care","name":"Stainless steel painless q whole body depilation instrument","price":27.13,"image":"images/per021.jpg","source":"https://crossbeez.com/product?id=841"},
  "per022": {"sku":"per022","section":"Personal Care","name":"Electric women's shaver","price":65,"image":"images/per022.jpg","source":"https://crossbeez.com/product?id=842"},
  "per023": {"sku":"per023","section":"Personal Care","name":"Women's electric shaver","price":99.59,"image":"images/per023.jpg","source":"https://crossbeez.com/product?id=843"},
  "per024": {"sku":"per024","section":"Personal Care","name":"5 in 1 body epilator","price":126,"image":"images/per024.jpg","source":"https://crossbeez.com/product?id=844"},
  "per025": {"sku":"per025","section":"Personal Care","name":"2 In 1 Electric Epilator For Women","price":142.69,"image":"images/per025.jpg","source":"https://crossbeez.com/product?id=845"},
  "per026": {"sku":"per026","section":"Personal Care","name":"Portable USB Rechargeable 4-in-1 Epilator Trimmer","price":56.55,"image":"images/per026.jpg","source":"https://crossbeez.com/product?id=846"},
  "per027": {"sku":"per027","section":"Personal Care","name":"Ladies electric shaver epilator","price":32.85,"image":"images/per027.jpg","source":"https://crossbeez.com/product?id=847"},
  "per028": {"sku":"per028","section":"Personal Care","name":"Women's bikini trimmer","price":89.99,"image":"images/per028.jpg","source":"https://crossbeez.com/product?id=884"},
  "per029": {"sku":"per029","section":"Personal Care","name":"Women's electric razor","price":72.48,"image":"images/per029.jpg","source":"https://crossbeez.com/product?id=885"},
  "per030": {"sku":"per030","section":"Personal Care","name":"Painless Women's Bikini Trimmer","price":92.36,"image":"images/per030.jpg","source":"https://crossbeez.com/product?id=886"},
  "per031": {"sku":"per031","section":"Personal Care","name":"Electric bikini trimmer","price":62.78,"image":"images/per031.jpg","source":"https://crossbeez.com/product?id=887"},
  "per032": {"sku":"per032","section":"Personal Care","name":"Waterproof wet and dry body hair trimmer","price":77.26,"image":"images/per032.jpg","source":"https://crossbeez.com/product?id=888"},
  "per033": {"sku":"per033","section":"Personal Care","name":"Cordless lady electric trimmer","price":84.17,"image":"images/per033.jpg","source":"https://crossbeez.com/product?id=889"},
  "per034": {"sku":"per034","section":"Personal Care","name":"Portable Rechargeable Electric Shaver for Women","price":95.48,"image":"images/per034.jpg","source":"https://crossbeez.com/product?id=890"},
  "per035": {"sku":"per035","section":"Personal Care","name":"3 in 1 rechargeable electric shaver for women","price":63.99,"image":"images/per035.jpg","source":"https://crossbeez.com/product?id=891"},
  "per036": {"sku":"per036","section":"Personal Care","name":"Women's electric razor bikini trimmer","price":75.89,"image":"images/per036.jpg","source":"https://crossbeez.com/product?id=892"},
  "per037": {"sku":"per037","section":"Personal Care","name":"2-in-1 double-head electric women's trimmer","price":90,"image":"images/per037.jpg","source":"https://crossbeez.com/product?id=893"},
  "per038": {"sku":"per038","section":"Personal Care","name":"Rechargeable, wet and dry use, painless women's razor","price":66.99,"image":"images/per038.jpg","source":"https://crossbeez.com/product?id=894"},
  "per039": {"sku":"per039","section":"Personal Care","name":"Ceramic curling iron","price":28.99,"image":"images/per039.jpg","source":"https://crossbeez.com/product?id=910"},
  "per040": {"sku":"per040","section":"Personal Care","name":"1 inch (approximately 2.5 cm) curling iron","price":40.33,"image":"images/per040.jpg","source":"https://crossbeez.com/product?id=911"},
  "per041": {"sku":"per041","section":"Personal Care","name":"6 in 1 curling iron","price":65.95,"image":"images/per041.jpg","source":"https://crossbeez.com/product?id=912"},
  "per042": {"sku":"per042","section":"Personal Care","name":"Electric shaver nose hair trimmer","price":76.98,"image":"images/per042.jpg","source":"https://crossbeez.com/product?id=913"},
  "per043": {"sku":"per043","section":"Personal Care","name":"Lithium titanium foil razor","price":39.99,"image":"images/per043.jpg","source":"https://crossbeez.com/product?id=914"},
  "per044": {"sku":"per044","section":"Personal Care","name":"Electric shaver with pop-up trimmer","price":68.28,"image":"images/per044.jpg","source":"https://crossbeez.com/product?id=915"},
  "per045": {"sku":"per045","section":"Personal Care","name":"Comes with 2-in-1 dual-blade shaver","price":55.69,"image":"images/per045.jpg","source":"https://crossbeez.com/product?id=916"},
  "per046": {"sku":"per046","section":"Personal Care","name":"Head electric shaver","price":60.5,"image":"images/per046.jpg","source":"https://crossbeez.com/product?id=917"},
  "per047": {"sku":"per047","section":"Personal Care","name":"High-speed hair dryer Thermal controlled small hair dryer","price":96.99,"image":"images/per047.jpg","source":"https://crossbeez.com/product?id=918"},
  "per048": {"sku":"per048","section":"Personal Care","name":"Hair dryer and hot air comb","price":77.67,"image":"images/per048.jpg","source":"https://crossbeez.com/product?id=919"},
  "per049": {"sku":"per049","section":"Personal Care","name":"1PC electric depilation instrument portable","price":54.98,"image":"images/per049.jpg","source":"https://crossbeez.com/product?id=983"},
  "per050": {"sku":"per050","section":"Personal Care","name":"Electric hair removal device for women","price":49.99,"image":"images/per050.jpg","source":"https://crossbeez.com/product?id=984"},
  "per051": {"sku":"per051","section":"Personal Care","name":"Women's electric shaver, waterproof, wet and dry use","price":112.76,"image":"images/per051.jpg","source":"https://crossbeez.com/product?id=985"},
  "com001": {"sku":"com001","section":"Home Comfort","name":"Desktop Humidifier","price":49.99,"image":"images/com001.png","source":"https://crossbeez.com/product?id=716"},
  "com002": {"sku":"com002","section":"Home Comfort","name":"Ultrasonic Household Humidifier","price":69.99,"image":"images/com002.png","source":"https://crossbeez.com/product?id=717"},
  "com003": {"sku":"com003","section":"Home Comfort","name":"Office Desktop Mini Humidifier","price":54.98,"image":"images/com003.png","source":"https://crossbeez.com/product?id=718"},
  "com004": {"sku":"com004","section":"Home Comfort","name":"Bedroom Bedside Humidifier","price":29.99,"image":"images/com004.png","source":"https://crossbeez.com/product?id=719"},
  "com005": {"sku":"com005","section":"Home Comfort","name":"Top Filling Humidifier","price":94.98,"image":"images/com005.png","source":"https://crossbeez.com/product?id=720"},
  "com006": {"sku":"com006","section":"Home Comfort","name":"Munchkin Usb Humidifier","price":85.98,"image":"images/com006.png","source":"https://crossbeez.com/product?id=722"},
  "com007": {"sku":"com007","section":"Home Comfort","name":"Small Air Hydration Humidifier","price":134.98,"image":"images/com007.png","source":"https://crossbeez.com/product?id=723"},
  "com008": {"sku":"com008","section":"Home Comfort","name":"3l Large Capacity Humidifier","price":109.98,"image":"images/com008.png","source":"https://crossbeez.com/product?id=724"},
  "com009": {"sku":"com009","section":"Home Comfort","name":"Mini Budgie Humidifier","price":76.98,"image":"images/com009.png","source":"https://crossbeez.com/product?id=725"},
  "com010": {"sku":"com010","section":"Home Comfort","name":"Classic Small Desk Fan","price":29.99,"image":"images/com010.png","source":"https://crossbeez.com/product?id=726"},
  "com011": {"sku":"com011","section":"Home Comfort","name":"USB Fan for Desk","price":69.99,"image":"images/com011.png","source":"https://crossbeez.com/product?id=727"},
  "com012": {"sku":"com012","section":"Home Comfort","name":"Personal USB Desk Fan","price":47.96,"image":"images/com012.jpg","source":"https://crossbeez.com/product?id=728"},
  "com013": {"sku":"com013","section":"Home Comfort","name":"Super Car Fan","price":54.98,"image":"images/com013.png","source":"https://crossbeez.com/product?id=729"},
  "com014": {"sku":"com014","section":"Home Comfort","name":"Magic little fan for office","price":49.91,"image":"images/com014.png","source":"https://crossbeez.com/product?id=730"},
  "com015": {"sku":"com015","section":"Home Comfort","name":"Desk Fan with LED Light","price":39.99,"image":"images/com015.png","source":"https://crossbeez.com/product?id=731"},
  "com016": {"sku":"com016","section":"Home Comfort","name":"Oscillating USB Desk Fan","price":75.98,"image":"images/com016.png","source":"https://crossbeez.com/product?id=732"},
  "com017": {"sku":"com017","section":"Home Comfort","name":"Mini pocket fan","price":59.99,"image":"images/com017.png","source":"https://crossbeez.com/product?id=733"},
  "com018": {"sku":"com018","section":"Home Comfort","name":"Portable USB Rechargeable Fan","price":94.98,"image":"images/com018.png","source":"https://crossbeez.com/product?id=734"},
  "com019": {"sku":"com019","section":"Home Comfort","name":"8-Inch Battery Operated Clip on Fan","price":58.98,"image":"images/com019.png","source":"https://crossbeez.com/product?id=735"},
  "com020": {"sku":"com020","section":"Home Comfort","name":"Portable Ceramic Space Heater","price":103.98,"image":"images/com020.png","source":"https://crossbeez.com/product?id=736"},
  "com021": {"sku":"com021","section":"Home Comfort","name":"1500W Indoor Electric Portable Heaters","price":133.98,"image":"images/com021.png","source":"https://crossbeez.com/product?id=737"},
  "com022": {"sku":"com022","section":"Home Comfort","name":"Rapid heating mobile heater","price":129.99,"image":"images/com022.png","source":"https://crossbeez.com/product?id=738"},
  "com023": {"sku":"com023","section":"Home Comfort","name":"Small Space Heater Electric Portable Heater Fan","price":119.98,"image":"images/com023.png","source":"https://crossbeez.com/product?id=739"},
  "com024": {"sku":"com024","section":"Home Comfort","name":"Portable portable heater","price":159.99,"image":"images/com024.png","source":"https://crossbeez.com/product?id=740"},
  "com025": {"sku":"com025","section":"Home Comfort","name":"Desk Heater Portable Heater","price":150.98,"image":"images/com025.png","source":"https://crossbeez.com/product?id=741"},
  "com026": {"sku":"com026","section":"Home Comfort","name":"A must-have quick heater for your home","price":108.98,"image":"images/com026.png","source":"https://crossbeez.com/product?id=742"},
  "com027": {"sku":"com027","section":"Home Comfort","name":"Small Space Heaters for Indoor Use","price":199.99,"image":"images/com027.png","source":"https://crossbeez.com/product?id=743"},
  "com028": {"sku":"com028","section":"Home Comfort","name":"Heater suitable for guest restaurant","price":168.95,"image":"images/com028.png","source":"https://crossbeez.com/product?id=744"},
  "com029": {"sku":"com029","section":"Home Comfort","name":"24\" Space Heater","price":199.99,"image":"images/com029.png","source":"https://crossbeez.com/product?id=745"},
  "com030": {"sku":"com030","section":"Home Comfort","name":"Large panel heated coaster","price":6.66,"image":"images/com030.png","source":"https://crossbeez.com/product?id=748"},
  "com031": {"sku":"com031","section":"Home Comfort","name":"300W fast heating four-speed thermostat coaster","price":134.98,"image":"images/com031.jpg","source":"https://crossbeez.com/product?id=750"},
  "com032": {"sku":"com032","section":"Home Comfort","name":"55 degree smart thermostatic coaster","price":2,"image":"images/com032.jpg","source":"https://crossbeez.com/product?id=751"},
  "com033": {"sku":"com033","section":"Home Comfort","name":"Three levels of thermal insulation and constant temperatu...","price":67.23,"image":"images/com033.jpg","source":"https://crossbeez.com/product?id=752"},
  "com034": {"sku":"com034","section":"Home Comfort","name":"Insulated coaster 75 degrees","price":56.98,"image":"images/com034.jpg","source":"https://crossbeez.com/product?id=754"},
  "com035": {"sku":"com035","section":"Home Comfort","name":"Heating Coaster Constant Temperature Coaster","price":53.78,"image":"images/com035.jpg","source":"https://crossbeez.com/product?id=755"},
  "com036": {"sku":"com036","section":"Home Comfort","name":"4-inch portable USB rechargeable desktop mini fan","price":35.99,"image":"images/com036.webp","source":"https://crossbeez.com/product?id=777"},
  "com037": {"sku":"com037","section":"Home Comfort","name":"600 ml USB air humidifier","price":89.98,"image":"images/com037.jpg","source":"https://crossbeez.com/product?id=792"},
  "com038": {"sku":"com038","section":"Home Comfort","name":"UFO Rain Cloud Humidifier Dropper","price":76.98,"image":"images/com038.jpg","source":"https://crossbeez.com/product?id=793"},
  "com039": {"sku":"com039","section":"Home Comfort","name":"300ml small onion air humidifier","price":39.99,"image":"images/com039.jpg","source":"https://crossbeez.com/product?id=794"},
  "com040": {"sku":"com040","section":"Home Comfort","name":"Ultrasonic cold fog air humidifier","price":56.98,"image":"images/com040.jpg","source":"https://crossbeez.com/product?id=795"},
  "com041": {"sku":"com041","section":"Home Comfort","name":"Travel Office Constant Temperature Coaster","price":25.36,"image":"images/com041.webp","source":"https://crossbeez.com/product?id=809"},
  "com042": {"sku":"com042","section":"Home Comfort","name":"USB constant temperature electric coaster","price":32,"image":"images/com042.webp","source":"https://crossbeez.com/product?id=815"},
  "com043": {"sku":"com043","section":"Home Comfort","name":"Top filling station humidifier","price":70.89,"image":"images/com043.jpg","source":"https://crossbeez.com/product?id=920"},
  "com044": {"sku":"com044","section":"Home Comfort","name":"Portable mini humidifier for bedroom","price":37.99,"image":"images/com044.jpg","source":"https://crossbeez.com/product?id=921"},
  "com045": {"sku":"com045","section":"Home Comfort","name":"Ultra-quiet three-in-one humidifier","price":65.98,"image":"images/com045.jpg","source":"https://crossbeez.com/product?id=922"},
  "com046": {"sku":"com046","section":"Home Comfort","name":"Top Fill Smart Plant Humidifier","price":75.98,"image":"images/com046.jpg","source":"https://crossbeez.com/product?id=923"},
  "com047": {"sku":"com047","section":"Home Comfort","name":"Humidifier Mist Vaporizer With Water Filter","price":29.99,"image":"images/com047.jpg","source":"https://crossbeez.com/product?id=977"},
  "com048": {"sku":"com048","section":"Home Comfort","name":"Cool Mist Humidifier For Bedroom","price":49.99,"image":"images/com048.jpg","source":"https://crossbeez.com/product?id=978"},
  "com049": {"sku":"com049","section":"Home Comfort","name":"Filterless Large Room Humidifiers","price":69.99,"image":"images/com049.jpg","source":"https://crossbeez.com/product?id=979"},
  "com050": {"sku":"com050","section":"Home Comfort","name":"Cool Mist Humidifiers With Oil Diffuser","price":54.98,"image":"images/com050.jpg","source":"https://crossbeez.com/product?id=980"},
  "com051": {"sku":"com051","section":"Home Comfort","name":"Ultrasonic Humidifier Mist Vaporizer","price":134.98,"image":"images/com051.jpg","source":"https://crossbeez.com/product?id=981"},
  "com052": {"sku":"com052","section":"Home Comfort","name":"Cool Mist Humidifier","price":94.98,"image":"images/com052.jpg","source":"https://crossbeez.com/product?id=982"},
  "com053": {"sku":"com053","section":"Home Comfort","name":"Smart Thermostat Coaster","price":29.99,"image":"images/com053.png","source":"https://crossbeez.com/product?id=1010"},
  "com054": {"sku":"com054","section":"Home Comfort","name":"Thermal Coaster","price":69.99,"image":"images/com054.png","source":"https://crossbeez.com/product?id=1012"},
  "com055": {"sku":"com055","section":"Home Comfort","name":"Digital Heating Coaster","price":30.25,"image":"images/com055.png","source":"https://crossbeez.com/product?id=1014"},
  "com056": {"sku":"com056","section":"Home Comfort","name":"Usb Insulation Coaster","price":30,"image":"images/com056.png","source":"https://crossbeez.com/product?id=1015"},
  "com057": {"sku":"com057","section":"Home Comfort","name":"Automatic Heating Coaster","price":39.99,"image":"images/com057.png","source":"https://crossbeez.com/product?id=1016"},
  "com058": {"sku":"com058","section":"Home Comfort","name":"Smart Power-off Coaster","price":40.33,"image":"images/com058.png","source":"https://crossbeez.com/product?id=1017"},
  "com059": {"sku":"com059","section":"Home Comfort","name":"Ceramic Heated Coaster","price":80.67,"image":"images/com059.png","source":"https://crossbeez.com/product?id=1018"},
  "com060": {"sku":"com060","section":"Home Comfort","name":"Bedroom top filling humidifier","price":49.99,"image":"images/com060.png","source":"https://crossbeez.com/product?id=1096"},
  "com061": {"sku":"com061","section":"Home Comfort","name":"5 liter bedroom humidifier","price":40.33,"image":"images/com061.png","source":"https://crossbeez.com/product?id=1097"},
  "com062": {"sku":"com062","section":"Home Comfort","name":"Small ultrasonic humidifier","price":35.99,"image":"images/com062.png","source":"https://crossbeez.com/product?id=1098"},
  "com063": {"sku":"com063","section":"Home Comfort","name":"Ultrasonic humidifier","price":56.89,"image":"images/com063.png","source":"https://crossbeez.com/product?id=1099"},
  "com064": {"sku":"com064","section":"Home Comfort","name":"Quiet 5-in-1 quality humidifier","price":66.89,"image":"images/com064.png","source":"https://crossbeez.com/product?id=1100"},
  "com065": {"sku":"com065","section":"Home Comfort","name":"Quiet ultrasonic humidifier","price":32.99,"image":"images/com065.png","source":"https://crossbeez.com/product?id=1101"},
  "com066": {"sku":"com066","section":"Home Comfort","name":"Evaporative humidifier","price":72.59,"image":"images/com066.png","source":"https://crossbeez.com/product?id=1102"},
  "com067": {"sku":"com067","section":"Home Comfort","name":"6 liter humidifier","price":69.99,"image":"images/com067.png","source":"https://crossbeez.com/product?id=1103"},
  "com068": {"sku":"com068","section":"Home Comfort","name":"500 ml desktop humidifier","price":128.98,"image":"images/com068.png","source":"https://crossbeez.com/product?id=1104"},
  "com069": {"sku":"com069","section":"Home Comfort","name":"Cool Mist Top Fill Essential Oil Humidifier","price":36.65,"image":"images/com069.png","source":"https://crossbeez.com/product?id=1105"},
  "com070": {"sku":"com070","section":"Home Comfort","name":"Spray ultrasonic air humidifier","price":55.52,"image":"images/com070.png","source":"https://crossbeez.com/product?id=1106"},
  "com071": {"sku":"com071","section":"Home Comfort","name":"3.6 liter small humidifier","price":39.65,"image":"images/com071.png","source":"https://crossbeez.com/product?id=1107"},
  "com072": {"sku":"com072","section":"Home Comfort","name":"Black personal desk fan","price":28.98,"image":"images/com072.png","source":"https://crossbeez.com/product?id=1109"},
  "com073": {"sku":"com073","section":"Home Comfort","name":"Bedroom swing fan","price":36.78,"image":"images/com073.png","source":"https://crossbeez.com/product?id=1110"},
  "com074": {"sku":"com074","section":"Home Comfort","name":"Retro air circulation fan","price":55.86,"image":"images/com074.png","source":"https://crossbeez.com/product?id=1111"},
  "com075": {"sku":"com075","section":"Home Comfort","name":"Heavy air circulation fan","price":48.97,"image":"images/com075.png","source":"https://crossbeez.com/product?id=1112"},
  "com076": {"sku":"com076","section":"Home Comfort","name":"Energy-saving medium-sized air circulation fan","price":40.55,"image":"images/com076.png","source":"https://crossbeez.com/product?id=1113"},
  "com077": {"sku":"com077","section":"Home Comfort","name":"13 inch air circulation fan","price":63.58,"image":"images/com077.png","source":"https://crossbeez.com/product?id=1114"},
  "com078": {"sku":"com078","section":"Home Comfort","name":"Silent air circulation fan","price":38.88,"image":"images/com078.png","source":"https://crossbeez.com/product?id=1115"},
  "com079": {"sku":"com079","section":"Home Comfort","name":"4400mAh rechargeable silent desktop fan","price":45.36,"image":"images/com079.png","source":"https://crossbeez.com/product?id=1116"},
  "com080": {"sku":"com080","section":"Home Comfort","name":"Table fan 10 inch (about 25.4 cm) air circulator","price":42,"image":"images/com080.png","source":"https://crossbeez.com/product?id=1117"},
  "com081": {"sku":"com081","section":"Home Comfort","name":"Rechargeable LED lamp fan air cooler","price":33.35,"image":"images/com081.png","source":"https://crossbeez.com/product?id=1118"},
  "com082": {"sku":"com082","section":"Home Comfort","name":"Portable rechargeable clip fan","price":34.45,"image":"images/com082.png","source":"https://crossbeez.com/product?id=1119"},
  "com083": {"sku":"com083","section":"Home Comfort","name":"6-inch (about 15.2 cm) USB desk fan","price":28.84,"image":"images/com083.png","source":"https://crossbeez.com/product?id=1120"},
  "com084": {"sku":"com084","section":"Home Comfort","name":"Remote control whole house fan","price":44.65,"image":"images/com084.png","source":"https://crossbeez.com/product?id=1121"},
  "com085": {"sku":"com085","section":"Home Comfort","name":"Small swing head circulating fan","price":59.64,"image":"images/com085.png","source":"https://crossbeez.com/product?id=1122"},
  "com086": {"sku":"com086","section":"Home Comfort","name":"Mini modern personal retro air circulation fan","price":36.69,"image":"images/com086.png","source":"https://crossbeez.com/product?id=1123"},
  "com087": {"sku":"com087","section":"Home Comfort","name":"Lightweight mini travel fan","price":13.89,"image":"images/com087.png","source":"https://crossbeez.com/product?id=1124"},
  "tec001": {"sku":"tec001","section":"Tech","name":"Personalized Noise Cancellation and Sound","price":134.98,"image":"images/tec001.jpg","source":"https://crossbeez.com/product?id=670"},
  "tec002": {"sku":"tec002","section":"Tech","name":"USB electric haircut and sideburns trimming dual-purpose","price":49.99,"image":"images/tec002.png","source":"https://crossbeez.com/product?id=698"},
  "tec003": {"sku":"tec003","section":"Tech","name":"Hand Warmer Power Bank","price":49.99,"image":"images/tec003.png","source":"https://crossbeez.com/product?id=704"},
  "tec004": {"sku":"tec004","section":"Tech","name":"Flannel Cloth Hand Warmer Power Bank","price":69.99,"image":"images/tec004.jpg","source":"https://crossbeez.com/product?id=705"},
  "tec005": {"sku":"tec005","section":"Tech","name":"Hand Warmer Power Bank","price":54.98,"image":"images/tec005.png","source":"https://crossbeez.com/product?id=706"},
  "tec006": {"sku":"tec006","section":"Tech","name":"Mini Hand Warmer Power Bank","price":29.99,"image":"images/tec006.png","source":"https://crossbeez.com/product?id=707"},
  "tec007": {"sku":"tec007","section":"Tech","name":"Portable Hand Warmer Power Bank","price":94.98,"image":"images/tec007.png","source":"https://crossbeez.com/product?id=708"},
  "tec008": {"sku":"tec008","section":"Tech","name":"10000 mAh Power Bank Hand Warmer","price":84.98,"image":"images/tec008.png","source":"https://crossbeez.com/product?id=709"},
  "tec009": {"sku":"tec009","section":"Tech","name":"Multi-Function Power Bank Hand Warmer","price":105.95,"image":"images/tec009.png","source":"https://crossbeez.com/product?id=710"},
  "tec010": {"sku":"tec010","section":"Tech","name":"Creative Power Bank Hand Warmer","price":39.99,"image":"images/tec010.png","source":"https://crossbeez.com/product?id=711"},
  "tec011": {"sku":"tec011","section":"Tech","name":"Explosion-Proof Power Bank Hand Warmer","price":134.98,"image":"images/tec011.png","source":"https://crossbeez.com/product?id=712"},
  "tec012": {"sku":"tec012","section":"Tech","name":"2-in-1 Power Bank Hand Warmer","price":78.96,"image":"images/tec012.png","source":"https://crossbeez.com/product?id=713"},
  "tec013": {"sku":"tec013","section":"Tech","name":"Cartoon Hand Warmer Power Bank","price":119.99,"image":"images/tec013.png","source":"https://crossbeez.com/product?id=714"},
  "tec014": {"sku":"tec014","section":"Tech","name":"12-Portable USB Hand Warmer Power Bank","price":65.98,"image":"images/tec014.png","source":"https://crossbeez.com/product?id=715"},
  "tec015": {"sku":"tec015","section":"Tech","name":"55 degrees long-lasting temperature lock","price":28.99,"image":"images/tec015.png","source":"https://crossbeez.com/product?id=747"},
  "tec016": {"sku":"tec016","section":"Tech","name":"Wide Mouth Juice Extractor","price":68.99,"image":"images/tec016.webp","source":"https://crossbeez.com/product?id=967"},
  "tec017": {"sku":"tec017","section":"Tech","name":"Small room air purifier","price":56.98,"image":"images/tec017.png","source":"https://crossbeez.com/product?id=1086"},
  "tec018": {"sku":"tec018","section":"Tech","name":"Household air purifier","price":88.58,"image":"images/tec018.png","source":"https://crossbeez.com/product?id=1087"},
  "tec019": {"sku":"tec019","section":"Tech","name":"Odor elimination air purifier","price":108.59,"image":"images/tec019.png","source":"https://crossbeez.com/product?id=1091"},
  "tec020": {"sku":"tec020","section":"Tech","name":"Air purifier suitable for bedroom, nursery and living room","price":94.98,"image":"images/tec020.png","source":"https://crossbeez.com/product?id=1092"},
  "tec021": {"sku":"tec021","section":"Tech","name":"Household intelligent air purifier","price":136.95,"image":"images/tec021.png","source":"https://crossbeez.com/product?id=1093"},
  "tec022": {"sku":"tec022","section":"Tech","name":"Intelligent air purifier","price":89.98,"image":"images/tec022.png","source":"https://crossbeez.com/product?id=1094"},
  "tec023": {"sku":"tec023","section":"Tech","name":"Air purifier for whole family","price":96.67,"image":"images/tec023.png","source":"https://crossbeez.com/product?id=1095"}
};

window.HOMEOFTEN.BUNDLES = [
  {slug:"morning-coffee",title:"Morning Coffee Setup",section:"Kitchen",tagline:"Espresso machine, electric kettle, and a warming coaster — the three pieces that get you out the door before 8am.",code:"COFFEE30",discountPct:0.30,skus:["kit054","kit005","kit003"],coverSku:"kit054"},
  {slug:"fresh-juice-set",title:"Fresh Juice Set",section:"Kitchen",tagline:"Citrus juicer, portable blender, and personal smoothie mixer — three ways to drink your vegetables.",code:"JUICE30",discountPct:0.30,skus:["kit044","kit068","kit071"],coverSku:"kit044"},
  {slug:"whole-home-clean",title:"Whole Home Clean",section:"Cleaning",tagline:"All-in-one vacuum + sweep + mop, a cordless wet/dry vacuum, and a household air cleaner. The trio that handles every room.",code:"CLEAN30",discountPct:0.30,skus:["cln001","cln017","cln042"],coverSku:"cln001"},
  {slug:"quick-tidy-kit",title:"Quick Tidy Kit",section:"Cleaning",tagline:"Handheld vacuum, automatic floor sweeper, and air cleaner — for the daily ten-minute reset.",code:"TIDY30",discountPct:0.30,skus:["cln018","cln028","cln042"],coverSku:"cln018"},
  {slug:"smart-pet-set",title:"Smart Pet Set",section:"Pet",tagline:"Smart Wi-Fi feeder, water dispenser, and the double-meal camera feeder. Three pieces, one fed-and-watered pet, even when you're out.",code:"SMARTPET30",discountPct:0.30,skus:["pet003","pet007","pet020"],coverSku:"pet003"},
  {slug:"pet-essentials",title:"Pet Feeding Essentials",section:"Pet",tagline:"Automatic feeder, water dispenser, and combo feeder-water set. The starter trio for a new pet.",code:"PETKIT30",discountPct:0.30,skus:["pet001","pet014","pet017"],coverSku:"pet001"},
  {slug:"hair-tools-trio",title:"Hair Tools Trio",section:"Personal Care",tagline:"High-speed ionic dryer, French wave curling iron, and the no-damage hair straightener. The three pieces for any look.",code:"HAIR30",discountPct:0.30,skus:["per004","per008","per007"],coverSku:"per004"},
  {slug:"smooth-skin-set",title:"Smooth Skin Set",section:"Personal Care",tagline:"5-in-1 body epilator, women's electric shaver, and a bikini trimmer. Built for at-home grooming.",code:"SKIN30",discountPct:0.30,skus:["per024","per022","per028"],coverSku:"per024"},
  {slug:"sleep-better-bundle",title:"Sleep Better Bundle",section:"Home Comfort",tagline:"Bedside humidifier, small desk fan, and a portable space heater. Built for the wind-down hour.",code:"SLEEP30",discountPct:0.30,skus:["com001","com010","com020"],coverSku:"com001"},
  {slug:"cozy-corner-kit",title:"Cozy Corner Kit",section:"Home Comfort",tagline:"Cool-mist humidifier with diffuser, smart power-off coaster, and a mini pocket fan. The desk-side set.",code:"COZY30",discountPct:0.30,skus:["com050","com058","com017"],coverSku:"com050"},
  {slug:"daily-power-pack",title:"Daily Power Pack",section:"Tech",tagline:"Three high-capacity power bank hand warmers — 10000mAh, multi-function, and a regular. Charge anything, keep your hands warm.",code:"POWER30",discountPct:0.30,skus:["tec008","tec005","tec009"],coverSku:"tec008"},
  {slug:"clean-air-set",title:"Clean Air Set",section:"Tech",tagline:"Three air purifiers — small room, bedroom, and intelligent whole-home. Place one in each room.",code:"AIR30",discountPct:0.30,skus:["tec017","tec020","tec022"],coverSku:"tec017"},
];

window.HOMEOFTEN.QUIZZES = [

  /* ─── KITCHEN ─── */

  { slug:'find-your-coffee-setup', section:'Kitchen', title:'Find your coffee setup', eyebrow:'Quiz · 8 questions', lead:'Espresso, drip, or instant? Tell us how you take your morning coffee and we\'ll match three pieces.', coverSku:'kit054',
    questions:[
      { id:'style', question:'How do you take your coffee most days?', options:[
        { value:'espresso', label:'Espresso shots', emoji:'☕' },
        { value:'drip', label:'Drip / pour-over', emoji:'⏳' },
        { value:'capsule', label:'Capsules / pods', emoji:'⚪' },
        { value:'instant', label:'Instant — warm cup will do', emoji:'⚡' },
      ]},
      { id:'volume', question:'How much do you drink in a day?', options:[
        { value:'1', label:'One cup', emoji:'☕' },
        { value:'2-3', label:'2–3 cups', emoji:'☕☕' },
        { value:'4+', label:'4+ cups', emoji:'☕☕☕' },
      ]},
      { id:'cup-warm', question:'Need a cup warmer at your desk?', options:[
        { value:'yes', label:'Yes — keep it hot', emoji:'🔥' },
        { value:'no', label:'No — I drink fast', emoji:'⚡' },
      ]},
      { id:'space', question:'Counter space?', options:[
        { value:'tight', label:'Tight — small is key', emoji:'◽' },
        { value:'medium', label:'Medium', emoji:'◧' },
        { value:'plenty', label:'Plenty', emoji:'⬜' },
      ]},
      { id:'fancy', question:'Milk frothing important?', options:[
        { value:'yes', label:'Yes — lattes daily', emoji:'☕' },
        { value:'no', label:'Black coffee only', emoji:'⚫' },
        { value:'sometimes', label:'Sometimes', emoji:'🌗' },
      ]},
      { id:'water', question:'Filtered or tap water?', options:[
        { value:'filtered', label:'Filtered', emoji:'💧' },
        { value:'tap', label:'Tap is fine', emoji:'🚰' },
      ]},
      { id:'kettle', question:'Need an electric kettle?', options:[
        { value:'yes', label:'Yes', emoji:'🫖' },
        { value:'no', label:'No', emoji:'🚫' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $100', emoji:'$' },
        { value:'mid', label:'$100–200', emoji:'$$' },
        { value:'high', label:'$200+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'espresso-default':{headline:'Your espresso setup',why:'Espresso machine, an electric kettle for the rinse cycle, and a warming coaster for the cup.',skus:['kit054','kit005','kit003']},
      'drip-default':{headline:'Your drip set',why:'A drip coffee machine, a slim electric kettle, and a smart warming coaster.',skus:['kit059','kit005','kit003']},
      'capsule-default':{headline:'Your capsule set',why:'Capsule coffee machine, electric kettle, and a heating coaster.',skus:['kit058','kit005','kit003']},
      'instant-default':{headline:'Your instant trio',why:'A 1.7L electric kettle, a portable boiling cup, and a warming coaster.',skus:['kit015','kit004','kit019']},
      'default':{headline:'Our coffee picks',why:'Espresso machine, electric kettle, and a warming coaster.',skus:['kit054','kit005','kit003']},
    },
  },

  { slug:'pick-your-morning-maker', section:'Kitchen', title:'Pick your morning maker', eyebrow:'Quiz · 8 questions', lead:'Waffles, pancakes, smoothies, or toast? Tell us what mornings look like and we\'ll line up three.', coverSku:'kit028',
    questions:[
      { id:'breakfast', question:'What\'s your usual breakfast?', options:[
        { value:'sweet', label:'Sweet — waffles, pancakes', emoji:'🥞' },
        { value:'toast', label:'Toast + spread', emoji:'🍞' },
        { value:'smoothie', label:'Smoothie / juice', emoji:'🥤' },
        { value:'cooked', label:'Cooked — eggs, savoury', emoji:'🍳' },
      ]},
      { id:'serve', question:'Cooking for how many?', options:[
        { value:'1', label:'Just me', emoji:'1' },
        { value:'2', label:'Two', emoji:'2' },
        { value:'family', label:'Family (3+)', emoji:'4+' },
      ]},
      { id:'time', question:'Time you can spend?', options:[
        { value:'5', label:'Under 5 min', emoji:'⏱' },
        { value:'15', label:'10–15 min', emoji:'⏰' },
        { value:'30', label:'20+ min', emoji:'🕯' },
      ]},
      { id:'effort', question:'Effort level?', options:[
        { value:'low', label:'Lazy — one button', emoji:'😴' },
        { value:'medium', label:'Some prep', emoji:'🌗' },
        { value:'high', label:'I enjoy cooking', emoji:'🎨' },
      ]},
      { id:'sweet-tooth', question:'Sweet tooth?', options:[
        { value:'big', label:'Yes', emoji:'🍯' },
        { value:'no', label:'No', emoji:'🌿' },
      ]},
      { id:'space', question:'Counter space?', options:[
        { value:'tight', label:'Tight', emoji:'◽' },
        { value:'plenty', label:'Plenty', emoji:'⬜' },
      ]},
      { id:'fryer', question:'Use an air fryer too?', options:[
        { value:'yes', label:'Yes — daily', emoji:'🍟' },
        { value:'sometimes', label:'Sometimes', emoji:'🌗' },
        { value:'no', label:'No', emoji:'🚫' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $50', emoji:'$' },
        { value:'mid', label:'$50–150', emoji:'$$' },
        { value:'high', label:'$150+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'sweet-default':{headline:'Your sweet-breakfast trio',why:'Heart-shape waffle maker, a small pancake maker, and a 4-slice toaster.',skus:['kit030','kit031','kit038']},
      'toast-default':{headline:'Your toast set',why:'4-slice toaster, a bread machine, and a panini-and-sandwich maker.',skus:['kit038','kit037','kit029']},
      'smoothie-default':{headline:'Your smoothie trio',why:'Portable blender, a citrus juicer, and a personal smoothie mixer.',skus:['kit068','kit044','kit071']},
      'cooked-default':{headline:'Your cooked-breakfast set',why:'Air fryer, an electric kettle, and a 4-slice toaster.',skus:['kit032','kit005','kit038']},
      'default':{headline:'Our morning picks',why:'Air fryer, 2-slice toaster, and a small pancake maker.',skus:['kit032','kit040','kit031']},
    },
  },

  /* ─── CLEANING ─── */

  { slug:'pick-your-vacuum', section:'Cleaning', title:'Pick your vacuum', eyebrow:'Quiz · 8 questions', lead:'Robot, cordless handheld, or full-size — tell us your floors and we\'ll match three.', coverSku:'cln001',
    questions:[
      { id:'home-size', question:'Home size?', options:[
        { value:'small', label:'Small — apt / 1-bed', emoji:'◽' },
        { value:'medium', label:'Medium — 2-3 bed', emoji:'◧' },
        { value:'large', label:'Large — 4+ bed', emoji:'⬜' },
      ]},
      { id:'floors', question:'Floor type?', options:[
        { value:'hard', label:'Hardwood / tile', emoji:'▦' },
        { value:'carpet', label:'Carpet', emoji:'▪' },
        { value:'mixed', label:'Mix', emoji:'◧' },
      ]},
      { id:'pets', question:'Pets at home?', options:[
        { value:'yes', label:'Yes — shedding', emoji:'🐕' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'frequency', question:'Cleaning frequency?', options:[
        { value:'daily', label:'Daily', emoji:'7' },
        { value:'weekly', label:'Weekly', emoji:'1' },
        { value:'monthly', label:'When needed', emoji:'?' },
      ]},
      { id:'hands-off', question:'Want it hands-off?', options:[
        { value:'yes', label:'Robot do it', emoji:'🤖' },
        { value:'mix', label:'Mix robot + manual', emoji:'🌗' },
        { value:'no', label:'I prefer manual', emoji:'✊' },
      ]},
      { id:'wet-mop', question:'Need wet-mop function?', options:[
        { value:'yes', label:'Yes', emoji:'💧' },
        { value:'no', label:'Dry only', emoji:'◯' },
      ]},
      { id:'storage', question:'Storage space?', options:[
        { value:'small', label:'Tight', emoji:'◽' },
        { value:'fine', label:'Plenty', emoji:'⬜' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $100', emoji:'$' },
        { value:'mid', label:'$100–200', emoji:'$$' },
        { value:'high', label:'$200+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'small-default':{headline:'Your small-home set',why:'A mini sweeping robot, a cordless handheld vacuum, and an air cleaner.',skus:['cln009','cln018','cln042']},
      'medium-default':{headline:'Your medium-home set',why:'All-in-one vacuum + sweep + mop, a handheld for stairs, and an air cleaner.',skus:['cln001','cln018','cln042']},
      'large-default':{headline:'Your large-home set',why:'Smart mopping vacuum, fully-automatic sweeping robot, and a large-room air cleaner.',skus:['cln003','cln005','cln044']},
      'default':{headline:'Our top three',why:'All-in-one vacuum + sweep + mop, a smart sweeping robot, and an air cleaner.',skus:['cln001','cln002','cln042']},
    },
  },

  { slug:'whats-your-cleaning-style', section:'Cleaning', title:'What\'s your cleaning style?', eyebrow:'Quiz · 8 questions', lead:'Daily quick reset, weekly deep clean, fully automated, or minimal? Tell us and we\'ll pick three.', coverSku:'cln017',
    questions:[
      { id:'style', question:'Your style?', options:[
        { value:'quick', label:'Daily quick reset', emoji:'⚡' },
        { value:'deep', label:'Weekly deep clean', emoji:'💪' },
        { value:'auto', label:'Fully automated', emoji:'🤖' },
        { value:'minimal', label:'Minimal', emoji:'🌿' },
      ]},
      { id:'who', question:'Who cleans?', options:[
        { value:'me', label:'Me', emoji:'1' },
        { value:'family', label:'Whole family', emoji:'👨‍👩‍👧' },
        { value:'help', label:'Hired help', emoji:'🧹' },
      ]},
      { id:'air-quality', question:'Care about air quality?', options:[
        { value:'high', label:'Yes — allergies', emoji:'🌸' },
        { value:'medium', label:'Some concern', emoji:'🌗' },
        { value:'no', label:'Not really', emoji:'✗' },
      ]},
      { id:'noise', question:'Noise tolerance?', options:[
        { value:'silent', label:'Silent please', emoji:'🤫' },
        { value:'medium', label:'OK with some', emoji:'◧' },
        { value:'fine', label:'No issue', emoji:'🔊' },
      ]},
      { id:'app-control', question:'App / WiFi control important?', options:[
        { value:'yes', label:'Yes', emoji:'📱' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $100', emoji:'$' },
        { value:'mid', label:'$100–200', emoji:'$$' },
        { value:'high', label:'$200+', emoji:'$$$' },
      ]},
      { id:'pets', question:'Pets at home?', options:[
        { value:'yes', label:'Yes', emoji:'🐾' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'kids', question:'Kids at home?', options:[
        { value:'yes', label:'Yes', emoji:'🧒' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
    ],
    outcomes:{
      'quick-default':{headline:'Your daily-reset set',why:'Cordless handheld vacuum, automatic floor sweeper, and an air cleaner.',skus:['cln018','cln026','cln042']},
      'deep-default':{headline:'Your deep-clean trio',why:'Full all-in-one vacuum, cordless wet/dry vacuum, and a large-room air cleaner.',skus:['cln001','cln017','cln044']},
      'auto-default':{headline:'Your fully-automated set',why:'WiFi sweeping robot, smart mopping robot, and an intelligent air purifier.',skus:['cln021','cln003','cln045']},
      'minimal-default':{headline:'Your minimal set',why:'Mini sweeper, handheld vacuum, and a small air cleaner.',skus:['cln036','cln022','cln042']},
      'default':{headline:'Our top three',why:'All-in-one vacuum, automatic sweeper, and an air cleaner.',skus:['cln001','cln026','cln042']},
    },
  },

  /* ─── PET ─── */

  { slug:'find-your-pet-feeder', section:'Pet', title:'Find your pet\'s feeder', eyebrow:'Quiz · 8 questions', lead:'Automatic, timed, WiFi, or camera? Tell us about your pet and your schedule and we\'ll match three.', coverSku:'pet003',
    questions:[
      { id:'pet', question:'Who are you feeding?', options:[
        { value:'cat', label:'A cat', emoji:'🐈' },
        { value:'dog', label:'A dog', emoji:'🐕' },
        { value:'both', label:'Both', emoji:'🐾' },
      ]},
      { id:'meals', question:'Meals per day?', options:[
        { value:'1', label:'One', emoji:'1' },
        { value:'2', label:'Two', emoji:'2' },
        { value:'3+', label:'Three or more', emoji:'3+' },
      ]},
      { id:'travel', question:'Travel often?', options:[
        { value:'often', label:'Often', emoji:'✈️' },
        { value:'sometimes', label:'Sometimes', emoji:'🌗' },
        { value:'rarely', label:'Rarely', emoji:'🏠' },
      ]},
      { id:'wifi', question:'Want WiFi / app control?', options:[
        { value:'yes', label:'Yes', emoji:'📱' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'camera', question:'Want a camera to watch them?', options:[
        { value:'yes', label:'Yes', emoji:'📷' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'water', question:'Water dispenser too?', options:[
        { value:'yes', label:'Yes', emoji:'💧' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'capacity', question:'Capacity needs?', options:[
        { value:'small', label:'Small — 1 pet', emoji:'1' },
        { value:'large', label:'Large — multi-day', emoji:'5+' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $50', emoji:'$' },
        { value:'mid', label:'$50–100', emoji:'$$' },
        { value:'high', label:'$100+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'cat-default':{headline:'Your cat-feeding set',why:'Baby cat feeder, water dispenser, and a hanging drink feeder.',skus:['pet015','pet007','pet016']},
      'dog-default':{headline:'Your dog-feeding set',why:'Smart pet feeder, double-meal camera feeder, and a water dispenser.',skus:['pet003','pet020','pet007']},
      'both-default':{headline:'Your multi-pet set',why:'WiFi automatic feeder, water dispenser, and a combo feeder + water set.',skus:['pet004','pet007','pet017']},
      'default':{headline:'Our pet picks',why:'Smart pet feeder, water dispenser, and timed feeder.',skus:['pet003','pet007','pet002']},
    },
  },

  { slug:'solve-your-pet-water', section:'Pet', title:'Solve your pet\'s water problem', eyebrow:'Quiz · 8 questions', lead:'Fountain, dispenser, or combo? Tell us how your pet drinks and we\'ll find three pieces.', coverSku:'pet007',
    questions:[
      { id:'drinker', question:'Is your pet a fussy drinker?', options:[
        { value:'yes', label:'Yes — needs fresh', emoji:'💧' },
        { value:'no', label:'No', emoji:'🚰' },
      ]},
      { id:'size', question:'Pet size?', options:[
        { value:'small', label:'Small', emoji:'🐾' },
        { value:'medium', label:'Medium', emoji:'🐕' },
        { value:'large', label:'Large', emoji:'🐺' },
      ]},
      { id:'home-out', question:'Hours pet is alone?', options:[
        { value:'short', label:'< 4 hours', emoji:'⏱' },
        { value:'long', label:'8+ hours', emoji:'⏰' },
      ]},
      { id:'feed-combo', question:'Combo feeder + water?', options:[
        { value:'yes', label:'Yes — one unit', emoji:'✓' },
        { value:'no', label:'Separate', emoji:'✗' },
      ]},
      { id:'multi', question:'Multiple pets?', options:[
        { value:'1', label:'One', emoji:'1' },
        { value:'2+', label:'Two or more', emoji:'2+' },
      ]},
      { id:'light', question:'Want LED indicator?', options:[
        { value:'yes', label:'Yes', emoji:'💡' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'capacity', question:'Capacity?', options:[
        { value:'2L', label:'2L (1–2 days)', emoji:'💧' },
        { value:'4L+', label:'4L+ (long days)', emoji:'💧💧' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $50', emoji:'$' },
        { value:'mid', label:'$50–100', emoji:'$$' },
        { value:'high', label:'$100+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'default':{headline:'Our pet-water picks',why:'A pet water dispenser, a 2L LED-lit dispenser, and a combo feeder + water set.',skus:['pet007','pet019','pet017']},
      'yes-default':{headline:'Your fussy-drinker set',why:'LED-lit 2L water dispenser, a hanging fresh-water dispenser, and a combo feeder.',skus:['pet019','pet016','pet017']},
      'no-default':{headline:'Your simple-drinker set',why:'Standard water dispenser, a combo feeder + water, and a dog/cat dispenser.',skus:['pet007','pet017','pet014']},
    },
  },

  /* ─── PERSONAL CARE ─── */

  { slug:'find-your-hair-tool', section:'Personal Care', title:'Find your hair tool', eyebrow:'Quiz · 8 questions', lead:'Curl, straight, blowout, or all? Tell us about your hair and your week.', coverSku:'per004',
    questions:[
      { id:'goal', question:'Your styling goal?', options:[
        { value:'curl', label:'Curl', emoji:'🌀' },
        { value:'straight', label:'Straighten', emoji:'〰️' },
        { value:'volume', label:'Volume / blowout', emoji:'💨' },
        { value:'all', label:'All of it', emoji:'✦' },
      ]},
      { id:'type', question:'Hair type?', options:[
        { value:'fine', label:'Fine', emoji:'🌾' },
        { value:'medium', label:'Medium', emoji:'🌿' },
        { value:'thick', label:'Thick', emoji:'🌳' },
      ]},
      { id:'length', question:'Length?', options:[
        { value:'short', label:'Short', emoji:'✂️' },
        { value:'mid', label:'Mid', emoji:'〰️' },
        { value:'long', label:'Long', emoji:'🌊' },
      ]},
      { id:'damage', question:'How concerned about heat damage?', options:[
        { value:'high', label:'Very', emoji:'🌸' },
        { value:'medium', label:'Some', emoji:'🌗' },
        { value:'low', label:'Not much', emoji:'🔥' },
      ]},
      { id:'time', question:'Time per styling?', options:[
        { value:'5', label:'5 min', emoji:'⏱' },
        { value:'15', label:'15 min', emoji:'⏰' },
        { value:'30', label:'30+ min', emoji:'🕯' },
      ]},
      { id:'travel', question:'Travel-friendly important?', options:[
        { value:'yes', label:'Yes', emoji:'✈️' },
        { value:'no', label:'No', emoji:'🏠' },
      ]},
      { id:'multi', question:'One tool that does it all?', options:[
        { value:'yes', label:'Yes — 5-in-1', emoji:'5' },
        { value:'no', label:'Separate tools', emoji:'3' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $80', emoji:'$' },
        { value:'mid', label:'$80–150', emoji:'$$' },
        { value:'high', label:'$150+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'curl-default':{headline:'Your curl set',why:'French wave curling iron, ceramic auto curling iron, and the high-speed dryer.',skus:['per008','per014','per004']},
      'straight-default':{headline:'Your straightener set',why:'Negative-ion straightener, electric splint, and the high-speed dryer.',skus:['per010','per007','per004']},
      'volume-default':{headline:'Your blowout set',why:'High-speed ionic dryer, one-step dryer-brush, and a hot air comb.',skus:['per004','per009','per048']},
      'all-default':{headline:'Your all-in-one set',why:'5-in-1 ultrasonic dryer with curling/straightening, the 2-in-1 straightener-curler, and the high-speed dryer.',skus:['per013','per011','per004']},
      'default':{headline:'Our hair picks',why:'High-speed ionic dryer, French wave curler, and a straightener.',skus:['per004','per008','per007']},
    },
  },

  { slug:'build-your-grooming-kit', section:'Personal Care', title:'Build your grooming kit', eyebrow:'Quiz · 8 questions', lead:'Shaver, trimmer, epilator, or full kit? Tell us what you need to manage at home.', coverSku:'per024',
    questions:[
      { id:'area', question:'Primary area?', options:[
        { value:'body', label:'Whole body', emoji:'🧍' },
        { value:'bikini', label:'Bikini line', emoji:'🌸' },
        { value:'face', label:'Face / brows', emoji:'👁️' },
        { value:'legs', label:'Legs only', emoji:'🦵' },
      ]},
      { id:'method', question:'Preferred method?', options:[
        { value:'shave', label:'Shave', emoji:'🪒' },
        { value:'epilate', label:'Epilate', emoji:'✦' },
        { value:'trim', label:'Trim only', emoji:'✂️' },
        { value:'mix', label:'Mix', emoji:'🌗' },
      ]},
      { id:'pain', question:'Pain tolerance?', options:[
        { value:'low', label:'Low — gentle', emoji:'🌸' },
        { value:'medium', label:'OK', emoji:'◧' },
        { value:'high', label:'High', emoji:'💪' },
      ]},
      { id:'wet-dry', question:'Wet & dry use?', options:[
        { value:'yes', label:'Yes — shower', emoji:'🚿' },
        { value:'no', label:'Dry only', emoji:'◯' },
      ]},
      { id:'cord', question:'Cord or rechargeable?', options:[
        { value:'cord', label:'Cord — uninterrupted', emoji:'🔌' },
        { value:'rech', label:'Rechargeable', emoji:'🔋' },
      ]},
      { id:'multi', question:'One tool or several?', options:[
        { value:'one', label:'One does all', emoji:'1' },
        { value:'set', label:'A set', emoji:'3' },
      ]},
      { id:'travel', question:'Travel-friendly?', options:[
        { value:'yes', label:'Yes', emoji:'✈️' },
        { value:'no', label:'No', emoji:'🏠' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $50', emoji:'$' },
        { value:'mid', label:'$50–100', emoji:'$$' },
        { value:'high', label:'$100+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'body-default':{headline:'Your whole-body set',why:'5-in-1 body epilator, 4-in-1 hair removal device, and a bikini trimmer.',skus:['per024','per016','per028']},
      'bikini-default':{headline:'Your bikini set',why:'Bikini trimmer, women\'s electric shaver, and a painless body epilator.',skus:['per028','per022','per018']},
      'legs-default':{headline:'Your legs set',why:'Body epilator, women\'s electric razor, and the 2-in-1 epilator-trimmer.',skus:['per024','per029','per025']},
      'default':{headline:'Our grooming picks',why:'5-in-1 body epilator, electric shaver, and a bikini trimmer.',skus:['per024','per022','per028']},
    },
  },

  /* ─── HOME COMFORT ─── */

  { slug:'pick-your-humidifier', section:'Home Comfort', title:'Pick your humidifier', eyebrow:'Quiz · 8 questions', lead:'Bedroom, office, or whole-home? Tell us about your space and we\'ll match three sized for it.', coverSku:'com001',
    questions:[
      { id:'room', question:'Which room?', options:[
        { value:'bedroom', label:'Bedroom', emoji:'🛏️' },
        { value:'office', label:'Office / desk', emoji:'💼' },
        { value:'living', label:'Living room', emoji:'🛋️' },
        { value:'whole', label:'Whole home', emoji:'🏠' },
      ]},
      { id:'size', question:'Room size?', options:[
        { value:'small', label:'Small', emoji:'◽' },
        { value:'medium', label:'Medium', emoji:'◧' },
        { value:'large', label:'Large', emoji:'⬜' },
      ]},
      { id:'why', question:'Main concern?', options:[
        { value:'dryskin', label:'Dry skin', emoji:'🌸' },
        { value:'sleep', label:'Sleep quality', emoji:'🌙' },
        { value:'allergies', label:'Allergies', emoji:'🤧' },
        { value:'plants', label:'Plants', emoji:'🪴' },
      ]},
      { id:'noise', question:'Noise sensitivity?', options:[
        { value:'silent', label:'Silent only', emoji:'🤫' },
        { value:'medium', label:'OK with some', emoji:'◧' },
        { value:'fine', label:'Don\'t mind', emoji:'🔊' },
      ]},
      { id:'oils', question:'Want oil diffuser too?', options:[
        { value:'yes', label:'Yes', emoji:'🌿' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'fill', question:'Top-fill or bottom?', options:[
        { value:'top', label:'Top-fill', emoji:'⬇️' },
        { value:'either', label:'Either', emoji:'🌗' },
      ]},
      { id:'capacity', question:'Tank size?', options:[
        { value:'small', label:'< 1L', emoji:'1' },
        { value:'medium', label:'1–4L', emoji:'4' },
        { value:'large', label:'5L+', emoji:'5+' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $50', emoji:'$' },
        { value:'mid', label:'$50–100', emoji:'$$' },
        { value:'high', label:'$100+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'bedroom-default':{headline:'Your bedroom set',why:'Bedside humidifier, 5L bedroom humidifier, and a quiet ultrasonic.',skus:['com004','com061','com065']},
      'office-default':{headline:'Your office set',why:'Office desktop mini humidifier, ultrasonic household, and a desk fan with LED light.',skus:['com003','com002','com015']},
      'living-default':{headline:'Your living-room set',why:'Top-filling station humidifier, large-room cool mist, and an oil-diffuser humidifier.',skus:['com043','com049','com050']},
      'whole-default':{headline:'Your whole-home set',why:'Filterless large-room humidifier, 6-liter humidifier, and an ultrasonic vaporizer.',skus:['com049','com067','com051']},
      'default':{headline:'Our humidifier picks',why:'Desktop humidifier, ultrasonic household, and a 5L bedroom humidifier.',skus:['com001','com002','com061']},
    },
  },

  { slug:'stay-warm-at-home', section:'Home Comfort', title:'Stay warm at home', eyebrow:'Quiz · 8 questions', lead:'Heater, warming coaster, or both? Tell us where you\'re cold and we\'ll line up three.', coverSku:'com020',
    questions:[
      { id:'where', question:'Where are you cold?', options:[
        { value:'bedroom', label:'Bedroom', emoji:'🛏️' },
        { value:'desk', label:'Desk', emoji:'💼' },
        { value:'living', label:'Living room', emoji:'🛋️' },
        { value:'whole', label:'Whole house', emoji:'🏠' },
      ]},
      { id:'level', question:'Heat level?', options:[
        { value:'mild', label:'Mild — chill off', emoji:'🌗' },
        { value:'medium', label:'Medium', emoji:'☀️' },
        { value:'high', label:'Strong — toasty', emoji:'🔥' },
      ]},
      { id:'portable', question:'Portable or fixed?', options:[
        { value:'portable', label:'Portable', emoji:'🚶' },
        { value:'fixed', label:'Fixed', emoji:'📍' },
      ]},
      { id:'cup', question:'Want cup-warmer for desk?', options:[
        { value:'yes', label:'Yes', emoji:'☕' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'duration', question:'How long per session?', options:[
        { value:'short', label:'Quick boost', emoji:'⚡' },
        { value:'long', label:'All evening', emoji:'🕯' },
      ]},
      { id:'kids', question:'Kids around?', options:[
        { value:'yes', label:'Yes — safety needed', emoji:'🧒' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'oscillate', question:'Oscillating / wide coverage?', options:[
        { value:'yes', label:'Yes', emoji:'↔️' },
        { value:'no', label:'Point heat', emoji:'➡️' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $80', emoji:'$' },
        { value:'mid', label:'$80–150', emoji:'$$' },
        { value:'high', label:'$150+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'bedroom-default':{headline:'Your bedroom-warmth set',why:'Portable ceramic space heater, an oscillating desk fan with LED, and a thermostatic coaster.',skus:['com020','com016','com053']},
      'desk-default':{headline:'Your desk-warmth set',why:'Desk heater, a smart thermostatic coaster, and a heating coaster.',skus:['com025','com032','com030']},
      'living-default':{headline:'Your living-room set',why:'Indoor portable heater, 24-inch space heater, and rapid-heating mobile heater.',skus:['com021','com029','com022']},
      'whole-default':{headline:'Your whole-home set',why:'Large space heater, indoor electric heater, and oscillating wide-coverage heater.',skus:['com027','com021','com029']},
      'default':{headline:'Our warmth picks',why:'Portable ceramic heater, a desk heater, and a smart thermostatic coaster.',skus:['com020','com025','com053']},
    },
  },

  /* ─── TECH ─── */

  { slug:'pick-your-power-bank', section:'Tech', title:'Pick your power bank', eyebrow:'Quiz · 8 questions', lead:'Capacity, hand-warmer combo, multi-function? Tell us how you use power.', coverSku:'tec008',
    questions:[
      { id:'capacity', question:'Capacity?', options:[
        { value:'small', label:'Small — phone top-up', emoji:'🔋' },
        { value:'medium', label:'10000 mAh', emoji:'🔋🔋' },
        { value:'large', label:'20000 mAh+', emoji:'🔋🔋🔋' },
      ]},
      { id:'warmer', question:'Hand-warmer combo?', options:[
        { value:'yes', label:'Yes — winter', emoji:'🔥' },
        { value:'no', label:'No', emoji:'❄️' },
      ]},
      { id:'portable', question:'How portable?', options:[
        { value:'pocket', label:'Pocket-sized', emoji:'👖' },
        { value:'bag', label:'Bag', emoji:'👜' },
        { value:'desk', label:'Desk-bound', emoji:'💼' },
      ]},
      { id:'devices', question:'How many devices to charge?', options:[
        { value:'1', label:'One — phone', emoji:'📱' },
        { value:'2', label:'Phone + something', emoji:'📱⌚' },
        { value:'3+', label:'Three or more', emoji:'📱💻⌚' },
      ]},
      { id:'fast', question:'Fast charging needed?', options:[
        { value:'yes', label:'Yes', emoji:'⚡' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'style', question:'Style preference?', options:[
        { value:'plain', label:'Plain', emoji:'◾' },
        { value:'cute', label:'Cartoon / cute', emoji:'🎀' },
        { value:'classy', label:'Sleek / leather', emoji:'🤎' },
      ]},
      { id:'rugged', question:'Rugged / explosion-proof?', options:[
        { value:'yes', label:'Yes', emoji:'🛡️' },
        { value:'no', label:'Standard', emoji:'◯' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $50', emoji:'$' },
        { value:'mid', label:'$50–100', emoji:'$$' },
        { value:'high', label:'$100+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'small-default':{headline:'Your pocket set',why:'Mini hand warmer power bank, creative cartoon power bank, and a portable power bank hand warmer.',skus:['tec006','tec010','tec007']},
      'medium-default':{headline:'Your everyday set',why:'10000 mAh power bank hand warmer, multi-function power bank, and a 12-portable USB hand warmer.',skus:['tec008','tec009','tec014']},
      'large-default':{headline:'Your high-capacity set',why:'Multi-function power bank, explosion-proof power bank, and a 2-in-1 power bank hand warmer.',skus:['tec009','tec011','tec012']},
      'default':{headline:'Our power picks',why:'10000 mAh power bank, multi-function power bank, and a hand warmer.',skus:['tec008','tec009','tec005']},
    },
  },

  { slug:'clean-air-for-your-space', section:'Tech', title:'Clean air for your space', eyebrow:'Quiz · 8 questions', lead:'Bedroom, whole-home, office, or small room? Tell us about the air you\'re trying to fix.', coverSku:'tec022',
    questions:[
      { id:'room', question:'Which room?', options:[
        { value:'bedroom', label:'Bedroom', emoji:'🛏️' },
        { value:'office', label:'Office', emoji:'💼' },
        { value:'living', label:'Living room', emoji:'🛋️' },
        { value:'whole', label:'Whole home', emoji:'🏠' },
      ]},
      { id:'concern', question:'Main concern?', options:[
        { value:'odor', label:'Odor', emoji:'👃' },
        { value:'allergens', label:'Allergens', emoji:'🌸' },
        { value:'dust', label:'Dust', emoji:'💨' },
        { value:'general', label:'General freshness', emoji:'🍃' },
      ]},
      { id:'smart', question:'Smart / app control?', options:[
        { value:'yes', label:'Yes', emoji:'📱' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'pets', question:'Pets at home?', options:[
        { value:'yes', label:'Yes', emoji:'🐾' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'nursery', question:'Nursery use?', options:[
        { value:'yes', label:'Yes — quiet needed', emoji:'👶' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'filter', question:'Replaceable filter?', options:[
        { value:'yes', label:'Yes', emoji:'✓' },
        { value:'no', label:'Filterless', emoji:'✗' },
      ]},
      { id:'monitor', question:'Air-quality monitoring?', options:[
        { value:'yes', label:'Yes', emoji:'📊' },
        { value:'no', label:'No', emoji:'✗' },
      ]},
      { id:'budget', question:'Budget?', options:[
        { value:'low', label:'Under $80', emoji:'$' },
        { value:'mid', label:'$80–150', emoji:'$$' },
        { value:'high', label:'$150+', emoji:'$$$' },
      ]},
    ],
    outcomes:{
      'bedroom-default':{headline:'Your bedroom set',why:'Bedroom + nursery air purifier, small room purifier, and an air-quality monitor purifier.',skus:['tec020','tec017','tec023']},
      'whole-default':{headline:'Your whole-home set',why:'Whole-family air purifier, intelligent household purifier, and a monitoring purifier.',skus:['tec023','tec021','tec022']},
      'office-default':{headline:'Your office set',why:'Small room purifier, household purifier, and an intelligent purifier.',skus:['tec017','tec018','tec022']},
      'default':{headline:'Our air picks',why:'Intelligent air purifier, household air purifier, and a small room purifier.',skus:['tec022','tec018','tec017']},
    },
  },

];
